### ISSUE TITLE
Cargo warning: doc comment not used

### ISSUE THREAD

**Issue by heartsucker** [rust-lang-nursery/error-chain#217] opened 2017-09-08 11:33 UTC
```
warning: doc comment not used by rustdoc
  --> src/error.rs:12:1
   |
12 | / error_chain! {
13 | |     foreign_links {
14 | |         ChronoParse(chrono::ParseError);
15 | |         DataEncoding(data_encoding::DecodeError);
...  |
47 | |     }
48 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by PaulBGD** [comment] 2017-09-28 20:16
Duplicate of #213 it looks like.

**Comment by Yamakaky** [comment] 2017-09-29 21:13
Yeah, please reopen if it's still a problem.

**Closed by Yamakaky** 2017-09-29 21:13 UTC
